### ISSUE TITLE
Why both composer and npm?

### ISSUE THREAD

**Issue by Ansem** [idmarinas/lotgd-game#561]
**Is your feature request related to a problem? Please describe.**
Why are two dependency managers required?

**Describe the solution you'd like**
Preferrably to only use composer. Installing nodejs on a clean server just to install a dependency  seems odd.

**Describe alternatives you've considered**
How much does the features and code differ from 1.1.2 besides security fixes and php standard updated to 7.x
(how hard would it be to port modules)

**Additional context**
Thanks in advance and sorry for all the questions. Just a rookie server admin trying to grasp the why's behind the how's

**Comment by morbus** [comment]
Two different managers for two different languages. composer is for the PHP dependencies, and npm is for the JavaScript dependencies. The dependencies do not (and could not) exist in a single repository.

**Comment by idmarinas** [comment]
Hello @Ansem :
I see this issue now (Dont ask me why I see closed issues ^_^) and I see that a collaborator close inssue, but not answer all questions.

Morbus are in correct, composer is for PHP and node for JavaScript, but in your production server, not need install node or any node package.  I use "gulp" (a node package) for build some parts of game, like javascript, theme....

Code differ from 1.1.2 (in actual released version 4.2.0) in much, for example:

- New translator system.
- Use Doctrine to access to database.
- Use Twig for templates.
- Use service manager (Laminas Service Manager)
- And other changes

You can see all changelog in [https://github.com/idmarinas/lotgd-game/blob/master/CHANGELOG.md](url)

Difficulty when port modules? It depends
- From version 1.1.2 to 4.2.0: I think is very dificult, because a lot of changes in game.
- From version 1.1.2 to 2.0.0: Is very easy, not need a lot of changes.
- The more complex the module, the more difficult it is to port it to the latest version.
- One option (but slow) is to go version by version, but as a general rule, it is not very complex.
- Visit this repository for a updated modules: [https://github.com/idmarinas/lotgd-modules](url)

Hope this helps you, and I'm sorry you didn't have all the answers asap.
